webtalk_init -webtalk_dir C:/4th-year-project/FPGA_ADC_interface/FPGA_ADC_interface.sim/sim_1/behav/xsim/xsim.dir/FPGA_ADC_interface_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Jan 20 18:34:39 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211126199_0_0_261" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1890d691-4f55-4489-a778-374ab94ef1cb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5f55b11459cc4fedbc4950b169c2e0e5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "16" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2700 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "3.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "40 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.73_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6640_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1418204942 -regid "211126199_0_0_261" -xml C:/4th-year-project/FPGA_ADC_interface/FPGA_ADC_interface.sim/sim_1/behav/xsim/xsim.dir/FPGA_ADC_interface_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/4th-year-project/FPGA_ADC_interface/FPGA_ADC_interface.sim/sim_1/behav/xsim/xsim.dir/FPGA_ADC_interface_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/4th-year-project/FPGA_ADC_interface/FPGA_ADC_interface.sim/sim_1/behav/xsim/xsim.dir/FPGA_ADC_interface_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
